# Generated by Django 3.2.9 on 2021-11-22 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password_plain', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('remember_token', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('card_brand', models.CharField(max_length=255)),
                ('card_last_four', models.CharField(max_length=4)),
                ('trial_ends_at', models.DateTimeField()),
                ('shop_domain', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('trial_starts_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_plan_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('price_cents', models.IntegerField()),
                ('sale_price_cents', models.IntegerField()),
                ('cost_cents', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField()),
                ('shipping_price', models.IntegerField()),
                ('note', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.admin')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.brand')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.producttype')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.style')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField()),
                ('apartment', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country_code', models.CharField(max_length=255)),
                ('zip', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('payment_ref', models.TextField()),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_amt_cents', models.IntegerField()),
                ('ship_charged_cents', models.IntegerField(null=True)),
                ('ship_cost_cents', models.IntegerField(null=True)),
                ('subtotal_cents', models.IntegerField()),
                ('total_cents', models.IntegerField()),
                ('shipper_name', models.TextField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.TextField()),
                ('tax_total_cents', models.IntegerField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.product')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.product'),
        ),
        migrations.AddField(
            model_name='admin',
            name='billing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_test.billingplan'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
