# Generated by Django 3.2.9 on 2021-11-22 04:26

from __future__ import unicode_literals

from django.db import close_old_connections, migrations
from django.contrib.auth.models import User

import csv
from datetime import datetime
import os


def load_user_data(apps, schema_editor):
    Admin = apps.get_model("code_test", "Admin")
    BillingPlan = apps.get_model("code_test", "BillingPlan")
    migration_path = os.path.dirname(os.path.realpath(__file__))
    data_path = '{}/../data/'.format(migration_path)
    with open('{}users.csv'.format(data_path)) as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)

        for row in reader:
            id=row[0]
            email = row[2]
            password_plain = row[4]
            is_enabled = True if row[14] == 1 else False
            
            user = User.objects.create_user(email, email, password_plain)
            billingplan, created = BillingPlan.objects.get_or_create(
                billing_plan_name=row[15]
            )

            admin, created = Admin.objects.get_or_create(
                id=id,
                name=row[1],
                password_plain=password_plain,
                shop_name=row[6],
                remember_token=row[7] if row[7] != "NULL" else None,
                created_at=row[8],
                updated_at=row[9],
                card_brand=row[10],
                card_last_four=row[11],
                trial_ends_at=row[12],
                shop_domain=row[13],
                billing_plan_id=billingplan.id,
                trial_starts_at=row[16],
                user_id=user.id,
            )



class Migration(migrations.Migration):

    dependencies = [
        ('code_test', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]

