# Generated by Django 3.2.9 on 2021-11-22 00:11

from __future__ import unicode_literals

from django.db import migrations
import csv
from datetime import datetime
import os


def load_product_data(apps, schema_editor):
    Product = apps.get_model("code_test", "Product")
    ProductType = apps.get_model("code_test", "ProductType")
    Style = apps.get_model("code_test", "Style")
    Brand = apps.get_model("code_test", "Brand")
    
    migration_path = os.path.dirname(os.path.realpath(__file__))
    data_path = '{}/../data/'.format(migration_path)
    with open('{}products.csv'.format(data_path)) as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)

        products = []

        for row in reader:
            style, created = Style.objects.get_or_create(
                style_name=row[3]
            )
            
            brand, created = Brand.objects.get_or_create(
                brand_name=row[4]
            )

            producttype, crated = ProductType.objects.get_or_create(
                product_type_name=row[8]
            )



            product, created = Product.objects.get_or_create(
                id=row[0],
                product_name=row[1],
                description=row[2],
                style_id=style.id,
                brand_id=brand.id,
                created_at=row[5],
                updated_at=row[6],
                url=row[7],
                product_type_id=producttype.id,
                shipping_price=row[9],
                note=row[10],
                admin_id=row[11],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('code_test', '0002_populate_users'),
    ]

    operations = [
        migrations.RunPython(load_product_data),
    ]
