# Generated by Django 3.2.9 on 2021-11-22 02:18

from __future__ import unicode_literals

from django.db import migrations
import csv
from datetime import datetime
import os


def load_inventory_data(apps, schema_editor):
    Inventory = apps.get_model("code_test", "Inventory")

    migration_path = os.path.dirname(os.path.realpath(__file__))
    data_path = '{}/../data/'.format(migration_path)
    with open('{}inventory.csv'.format(data_path)) as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)

        for row in reader:
            inventor, created = Inventory.objects.get_or_create(
                id=row[0],
                product_id=row[1],
                quantity=row[2],
                color=row[3],
                size=row[4],
                weight=row[5],
                price_cents=row[6],
                sale_price_cents=row[7],
                cost_cents=row[8],
                sku=row[9],
                length=row[10],
                width=row[11],
                height=row[12],
                note=row[13],
            )

class Migration(migrations.Migration):

    dependencies = [
        ('code_test', '0003_populate_products'),
    ]

    operations = [
        migrations.RunPython(load_inventory_data),
    ]
